Content.destroy_all
Category.destroy_all
Testimonial.destroy_all

#Testimonial

testi1 = Testimonial.create!(first_name: 'Daniel. J', last_name: 'Levitin', quote: '"We\'ve found compelling evidence that musical interventions can play a health-care role in settings ranging from operating rooms to family clinics,"', photo: 'http://www.innonavi.com/wp-content/uploads/2016/02/DanielLevitin_cArsenioCoroa-350x354.jpg', active: true )
testi2 = Testimonial.create!(first_name: 'Lisa', last_name: 'Hartling', quote: '"There is growing scientific evidence showing that the brain responds to music in very specific ways"', photo:'http://childhealth.cochrane.org/sites/childhealth.cochrane.org/files/public/uploads/Hartling%20September%202016.jpg', active: true )
testi3 = Testimonial.create!(first_name: 'Melanie', last_name: 'Kwan', quote: '"Active music engagement allowed the patients to reconnect with the healthy parts of themselves, even in the face of a debilitating condition or disease-related suffering"', photo: 'http://68.media.tumblr.com/7de1b6fb022a722dfc383ef81443161e/tumblr_inline_nmqkc9kJG11sf7n9q_1280.jpg', active: true )



 # Category

cat1 = Category.create!(name: 'Music on brain and body', description:'General effect of music on brain and body', photo:'http://art2.sewanee.edu/class/fypsummers/files/2014/08/con-doctor.jpg', active: true)
cat2 = Category.create!(name: 'Music in (children\'s) hospital and other care', description: 'General effect of music on children\'s hospital and other care', photo:'https://sobernation.com/wp-content/uploads/2013/08/music-as-medicine.jpg', active: true)
cat3 = Category.create!(name: 'Alzheimer / Dementia / Ageing brain', description:'General effect of music on Alzheimer / Dementia / ageing brain', photo:'http://maxpixel.freegreatpicture.com/static/photo/1x/Donald-Trump-Trump-Alzheimers-Warning-Dementia-1750965.jpg', active: true)
cat4 = Category.create!(name: 'Postoperative pain and anxiety', description:'General effect of music on postoperative pain and anxiety:', photo:'http://www.bite-the-dust.com/images/nprmusicmedicine.jpg', active: true)
cat5 = Category.create!(name: 'Oncology', description:'General effect of music in oncology', photo:'http://www.patientcareonline.com/sites/default/files/styles/max_width/public/images/media/Slide2_260.JPG?itok=BrehM8cE', active: true)
cat6 = Category.create!(name: 'Depression and anxiety', description:'General effect of music on Depression and anxiety', photo:'http://static.rappler.com/images/science-solitaire-music-as-medicine-20130404.jpg', active: true)
cat7 = Category.create!(name: 'Parkinson\'s', description:'General effect of music on Parkinson\'s', photo:'http://images.sxsw.com/XqKZzR7Lbz1qAd_aJ2SxgfFVT9E=/39x30:474x341/950x/images.sxsw.com/27/9aabe10c-c958-4e6a-be8e-7547d61f9374/PP65723.png', active: true)
cat8 = Category.create!(name: 'Coronary Heart Disease', description:'General effect of music on Coronary Heart Disease', photo:'https://ac-cdn.azureedge.net/infusionnewssiteimages/agingcare/d574b6d7-7cb0-4dda-9e71-5ce089eb4f56.jpg', active: true)
cat9 = Category.create!(name: 'ADHD / Autism', description:'General effect of music on ADHD / Autism', photo:'http://media.arkansasonline.com/img/photos/2015/06/16/web_music_therapy.jpg', active: true)

# Content

cont1=Content.create!(info_label: 'WHAT HAPPENS IN THE BRAIN WHEN YOU LISTEN TO MUSIC?', info_text:'Dutch neuropsychologist prof.dr. Erik Scherder.
Increase of communication between right and left brain lobe, stimulating COORDINATION between EMOTION AND BEHAVIOR.
Increase of communication between front and back, ENLARGING SOCIAL COGNITION (EMPATHY). 
All by playing, listening to, but also imagining MUSIC.', video:'https://www.youtube.com/embed/9Kq3rwjMxTE', photo:'', website_link:'',active: true, category: cat1)
cont2=Content.create!(info_label: "We found ENDOGENOUS DOPAMINE RELEASE in the striatum at peak emotional arousal DURING MUSIC LISTENING....", info_text:"Our results help to explain why MUSIC IS OF SUCH HIGH VALUE across all human societies...", video:'', photo:'', website_link: 'http://www.nature.com/neuro/journal/v14/n2/abs/nn.2726.html', active: true, category: cat1)
cont3=Content.create!(info_label: "What we talk about when we talk about Music As Medicine", info_text:'', video:'', photo:'', website_link:'http://syncproject.co/blog/2015/7/14/what-we-talk-about-when-we-talk-about-music-as-medicine',active: true, category: cat1)
cont4=Content.create!(info_label: "SCIENTISTS discover NEURONS synchronize to MUSIC!", info_text:'', video:'', photo:'', website_link:'http://syncproject.co/blog/2015/11/20/your-brain-synchronizes-to-music',active: true, category: cat1)
cont6=Content.create!(info_label: 'This study may contribute in the future to a better understanding of neuronal diseases as SCHIZOFRENIA and AUTISM that are affected by interference from RHYTMIC SYNCHRONY', info_text:'\n * ...RHYTMIC ACTIVITY in fixed frequencies is an important feature of... INFORMATION FLOW \n *...RHYTMIC SYNCHRONY is a key mechanism for... COMMUNICATION throughout the brain', video:'', photo:'', website_link:'https://www.sciencedaily.com/releases/2016/08/160825084853.htm#.V8BPGWJG5wI.facebook',active: true, category: cat1)
cont7=Content.create!(info_label: "How Playing Music Benefits Your Brain More Than Any Other Activitiy.", info_text:'', video:'', photo:'', website_link:'https://www.brainpickings.org/2015/01/29/music-brain-ted-ed/',active: true, category: cat1)
cont8=Content.create!(info_label: "Musical training can have a dramatic impact on your brain's structure, enhancing your memory, spatial reasoning and language skills.", info_text:'', video:'', photo:'', website_link:'https://www.theguardian.com/education/2016/oct/24/want-to-train-your-brain-forget-apps-learn-a-musical-instrument?CMP=Share_iOSApp_Other',active: true, category: cat1)
cont9=Content.create!(info_label: "Quoting Marianne Van Der Heijden, working at research group Music As Medicine inErasmusMC Rotterdam and Red Cross War Memorial Children's Hospital in Cape Town:", info_text:"“My #MusicAsMedicine research aims to discover the efficacy of music interventions in sick children. Of course research needs to be done in order to provide evidence-based innovations in healthcare, but to be honest I think that this mother's writing has outdone any of my publications.”", video:'', photo:'', website_link: 'http://www.huffingtonpost.com/jennifer-canvasser/when-music-mattered-more-to-my-son_b_9306650.html', active: true, category: cat2)
cont10=Content.create!(info_label: "Doctors at a hospital in Istanbul are turning to an unusual form of medicine - music.", info_text:'Music therapy may sound a strange approach to modern medicine but according to doctors at the Memorial hospital in the Turkish capital it is producing results. The man behind the drive is Professor Bingur Sonmez and he has been joined by his colleagues Dr Erol Can and Mehmet Susam in order to revive the traditional Islamic idea of music therapy. Pictured above: Dr Erol Can (centre), plays a yayli tanbur (an Ottoman violin) with Professor Bingur Sonmez (left) holding a flute and Mehmet Susam (right) playing guitar.', video:'', photo:'', website_link:'https://www.facebook.com/facultyofmedicine/photos/a.243863131306.144627.26170131306/10153215078246307/?type=3',active: true, category: cat2)
cont11=Content.create!(info_label: "Mini documentary about the effect of BEDSIDE MUSIC on Paediatric Department of two Dutch Academic Medical Centre (Groningen/Utrecht)! ", info_text:'', video:'https://www.youtube.com/watch?v=JmHEMRH-ejg', photo:'', website_link:'https://www.facebook.com/facultyofmedicine/photos/a.243863131306.144627.26170131306/10153215078246307/?type=3',active: true, category: cat2)
cont12=Content.create!(info_label: "Initial inspiration: documentary ALIVE INSIDE (2014), see these 3 minutes. ", info_text:'ALZHEIMER patients instantly revitalize through listening to music.
Curious how it works NEUROSCIENTIFICALLY? To be continued!', video:'https://www.youtube.com/watch?v=EgNLLelQYwI#action=share', photo:'', website_link:'https://www.facebook.com/facultyofmedicine/photos/a.243863131306.144627.26170131306/10153215078246307/?type=3',active: true, category: cat3)
cont13=Content.create!(info_label: "Music making supports cognitive health during ageing.", info_text:'Again, not only MAKING music will do this, also LISTENING TO and even IMAGINING it! And...it does so for FREE and WITHOUT any SIDE-EFFECTS;);) ** Curious why....? Keep on following! MUSICianship PROTECTS certain cognitive functions like MEMORY and SPEECH processing, as well as underlying brain structures, FROM the effects of typical AGING.', video:'https://www.youtube.com/watch?v=JmHEMRH-ejg', photo:'', website_link:'http://syncproject.co/blog/2015/11/18/music-making-supports-cognitive-health-during-aging',active: true, category: cat3)
cont14=Content.create!(info_label: "REDUCE of PAIN and ANALGESIA USE by MUSIC - article in The Lancet, aug 2015:", info_text:'Background Music is a non-invasive, safe, and inexpensive intervention that can be delivered easily and successfully.
Methods We included randomised controlled trials (RCTs) of adult patients undergoing surgical procedures, excluding those involving the central nervous system or head and neck, published in any language. 
Findings Music reduced postoperative pain, anxiety, and analgesia use, and increased patient satisfaction.
Interpretation Music could be offered as a way to help patients reduce pain and anxiety during the postoperative period. ', video:'https://www.youtube.com/watch?v=JmHEMRH-ejg', photo:'', website_link:"http://www.thelancet.com/journals/lancet/article/PIIS0140-6736\(15\)60169-6\/abstract",active: true, category: cat4)
cont15=Content.create!(info_label: "Music demonstrated to alleve cancer patient's symtpoms.", info_text:'', video:'',photo:'',website_link:'https://medicalxpress.com/news/2016-08-music-alleviate-cancer-patients-symptoms.html',active: true, category: cat5)
cont16=Content.create!(info_label: "Kan muziek kanker genezen? ", info_text:'Helaas niet, maar het kan wel een belangrijke rol spelen tijdens de behandeling. Margrethe Langer Bro onderzoekt of muziek een positieve invloed heeft op patiënten die een chemobehandeling ondergaan.', video:'',photo:'',website_link:'https://www.hifiklubben.nl/hifimagazine/goosebumps/2016/muziek-verlicht-pijn-tijdens-chemokuur/',active: true, category: cat6)
cont17=Content.create!(info_label: "We are looking forward to using music therapy to deliver better patient outcomes during cancer treatment. ", info_text:'', video:'',photo:'',website_link:'http://www.geekwire.com/2017/chemotherapy-surgery-david-bowie-music-helps-cancer-patients-heal/',active: true, category: cat6)
cont18=Content.create!(info_label: "Listening to moving MUSIC causes the brain to REALEASE DOPAMINE, a FEEL-GOOD CHEMICAL", info_text:'', video:'',photo:'',website_link:'http://www.seeker.com/why-music-makes-you-happy-1765157098.html',active: true, category: cat6)
cont19=Content.create!(info_label: "Neuroscience says listening to this song reduces anxiety by up to 65 precent.", info_text:'', video:'',photo:'',website_link:' http://www.inc.com/melanie-curtin/neuroscience-says-listening-to-this-one-song-reduces-anxiety-by-up-to-65-percent.html',active: true, category: cat6)
cont20=Content.create!(info_label: "Video might be of bad quality, but keep on watching as what you'll see is really AMAZING!", info_text:'Inspiring Video Shows the Effect Music Had For This Particular Person Living with #Parkinsons.', video:'https://youtu.be/qxDmP8c4QUI',photo:'',website_link:'',active: true, category: cat7)
cont21=Content.create!(info_label: "MUSIC LISTENING HAS A BENEFICIAL EFFECT on blood pressure, heart rate, respiratory rate, anxiety, and pain in persons with CORONARY HEART DISEASE!", info_text:'Nothing new;), as already published in 2009 (!). Hardly used though, although NO SIDE EFFECTS and very LOW COST.', video:'',photo:'',website_link:'http://www.ncbi.nlm.nih.gov/m/pubmed/19370642/',active: true, category: cat8)
cont22=Content.create!(info_label: "Music interventions reduce anxiety and distress and improve physiological responses such as heart rate and respiratory rate in medical patients.", info_text:'Individuals with coronary heart disease often suffer from severe distress, putting them at greater risk for complications, including sudden cardiac death.', video:'',photo:'',website_link:'http://www.cochrane.org/CD006577/VASC_music-to-reduce-stress-and-anxiety-for-people-with-coronary-heart-disease',active: true, category: cat9)
cont23=Content.create!(info_label: "What Can Music Do? Rethinking Autism Through Music Therapy", info_text:'....amid growing rates of autism diagnosis and demands for better understanding of the condition, researchers have begun to look for the neurological underpinnings to what Nordoff, Robbins, and other music therapists stumbled upon intuitively: that music can be a lifeline for people with all kinds of isolating physical, psychological, emotional, and neurological conditions', video:'',photo:'',website_link:'http://www.nyu.edu/about/news-publications/news/2016/july/autism-and-neurodiversity-at-nordoff-robbins-center-for-music-th.html',active: true, category: cat9)
cont24=Content.create!(info_label: "How Music is Being Treated to Treat Autism, an inspirational story", info_text: '', video:'',photo:'',website_link:'https://www.theguardian.com/music/2017/mar/01/autism-music-therapy-detroit',active: true, category: cat9)
